# Generated by Django 3.1.2 on 2020-10-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201009_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='users/profile_pics/default.jpg', upload_to='users/profile_pics'),
        ),
    ]
