# Generated by Django 3.1.2 on 2020-10-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_steps_to_do_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='steps',
            new_name='Step',
        ),
    ]
