# Generated by Django 3.1.2 on 2020-10-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndcc', '0002_auto_20201016_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
