# Generated by Django 3.1.2 on 2020-10-26 19:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dndcc', '0004_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='cha',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], verbose_name='charisma'),
        ),
        migrations.AlterField(
            model_name='character',
            name='clss',
            field=models.CharField(choices=[('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Fighter', 'Fighter'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], max_length=9),
        ),
        migrations.AlterField(
            model_name='character',
            name='con',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], verbose_name='constitution'),
        ),
        migrations.AlterField(
            model_name='character',
            name='dex',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], verbose_name='dexterity'),
        ),
        migrations.AlterField(
            model_name='character',
            name='inl',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], verbose_name='intelligence'),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='stn',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], verbose_name='strength'),
        ),
        migrations.AlterField(
            model_name='character',
            name='wis',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], verbose_name='wisdom'),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('mod', models.CharField(choices=[('str', 'Strength'), ('dex', 'Dexterity')], max_length=3)),
                ('diceNum', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18')], verbose_name='diceNum')),
                ('diceType', models.CharField(choices=[(4, 'd4'), (6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12')], max_length=3)),
                ('damType', models.CharField(choices=[('acid', 'acid'), ('bludgeoning', 'bludgeoning'), ('cold', 'cold'), ('fire', 'fire'), ('force', 'force'), ('lightning', 'lightning'), ('necrotic', 'necrotic'), ('piercing', 'piercing'), ('poison', 'poison'), ('psychic', 'psychic'), ('radiant', 'radiant'), ('slashing', 'slashing'), ('thunder', 'thunder')], max_length=11)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndcc.character')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('diceNum', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18')])),
                ('diceType', models.CharField(choices=[('4', 'd4'), ('6', 'd6'), ('8', 'd8'), ('10', 'd10'), ('12', 'd12')], max_length=3)),
                ('damType', models.CharField(choices=[('acid', 'acid'), ('bludgeoning', 'bludgeoning'), ('cold', 'cold'), ('fire', 'fire'), ('force', 'force'), ('lightning', 'lightning'), ('necrotic', 'necrotic'), ('piercing', 'piercing'), ('poison', 'poison'), ('psychic', 'psychic'), ('radiant', 'radiant'), ('slashing', 'slashing'), ('thunder', 'thunder')], max_length=11)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndcc.character')),
            ],
        ),
    ]
