# Generated by Django 3.1.2 on 2020-10-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndcc', '0005_auto_20201026_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='diceType',
            field=models.PositiveSmallIntegerField(choices=[(4, 'd4'), (6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12')]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='diceType',
            field=models.PositiveSmallIntegerField(choices=[(4, 'd4'), (6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12')]),
        ),
    ]
