# Generated by Django 3.1.2 on 2020-10-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndcc', '0006_auto_20201026_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='bonus',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
            preserve_default=False,
        ),
    ]
