# Generated by Django 3.1.2 on 2020-10-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krnotes', '0002_auto_20201009_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/uploads'),
        ),
    ]
